#!/usr/bin/env python3
"""
Analyse exact reachable positional-belief states for a PARLEY knowledge model.

The analysis does NOT cluster beliefs.

It reports two related state sets:

1) horizon set
   Exact beliefs generated by the same offline horizon max_steps=10 that
   full_belief_representatives.py currently uses for threshold derivation.

2) URC-closed set
   Exact knowledge contexts (xhat, yhat, belief) reachable after a perfect
   localization/reset, followed by deterministic belief prediction while
   *some* URC choice can still skip an update.

   Since tau_10 is the largest threshold, expansion continues while

       Gini(b) < tau_10

   and stops once tau_10 is reached. At that point every c in 1..10 would
   trigger localization under the current threshold semantics.

This is the more relevant count for an exact PRISM knowledge model without an
explicit step/age variable.

Expected repository layout:
    maps/map_<id>.csv
    full_belief_representatives.py

Examples:
    python analyse_exact_reachable_beliefs.py --maps 10
    python analyse_exact_reachable_beliefs.py --maps 10,14,23
    python analyse_exact_reachable_beliefs.py
"""

import argparse
import csv
import json
from collections import deque
from pathlib import Path

import full_belief_representatives as belief_impl


DEFAULT_FIRST_MAP = 10
DEFAULT_LAST_MAP = 99
DEFAULT_MAX_STEPS = 10
DEFAULT_P = 0.01
DEFAULT_TARGET = (9, 9)
DEFAULT_MAPS_DIR = "maps"
DEFAULT_OUTPUT_DIR = "exact_belief_reachability"

ROUND_DIGITS = 14
EPS = 1e-12


def load_map(path: Path):
    rows = []
    with path.open("r", newline="") as f:
        rows.extend(csv.reader(f))
    transposed = list(zip(*rows))
    return [row[::-1] for row in transposed]


def vector_key(vector):
    return tuple(round(float(v), ROUND_DIGITS) for v in vector)


def scaled_gini(vector):
    return int(round(
        belief_impl._representative_gini(vector) * 10000
    ))


def absolute_from_relative(vector, xhat, yhat, n):
    """
    Reconstruct the absolute positional belief for a reachable knowledge
    context. Reachable relative offsets should already lie in the grid.
    """
    relative = belief_impl._vector_to_relative(vector, n)
    absolute = {}

    for (dx, dy), probability in relative.items():
        x = xhat + dx
        y = yhat + dy

        if not (0 <= x <= n and 0 <= y <= n):
            raise ValueError(
                "Reachable exact belief contains an out-of-grid relative "
                f"state: xhat={xhat}, yhat={yhat}, dx={dx}, dy={dy}"
            )

        absolute[(x, y)] = absolute.get((x, y), 0.0) + probability

    return absolute


def exact_successor(vector, xhat, yhat, action, n, p):
    absolute = absolute_from_relative(
        vector, xhat, yhat, n
    )

    propagated = belief_impl._propagate_absolute(
        absolute, action, n, p
    )

    nxhat, nyhat = belief_impl._move(
        xhat, yhat, action, n
    )

    successor = belief_impl._relative_vector(
        propagated, nxhat, nyhat, n
    )

    return successor, nxhat, nyhat


def free_cells(map_data):
    size = len(map_data)
    result = []
    for x in range(size):
        for y in range(size):
            if int(map_data[x][y]) <= 9:
                result.append((x, y))
    return result


def analyse_map(
    map_id,
    map_data,
    target,
    p,
    max_steps,
):
    size = len(map_data)
    n = size - 1

    # Reuse the current implementation exactly for threshold derivation and
    # the current horizon candidate count.
    horizon_candidates, gini_by_age, controller = (
        belief_impl._generate_records(
            map_data, target, p, max_steps
        )
    )
    thresholds = belief_impl._thresholds(
        gini_by_age, max_steps
    )
    tau_max = int(thresholds[-1])

    # Exact certainty relative belief.
    certain_abs = {(0, 0): 1.0}
    certain_vector = belief_impl._relative_vector(
        certain_abs, 0, 0, n
    )

    # State IDs are global per distinct relative belief vector.
    belief_id_by_key = {}
    belief_vectors = []

    def get_belief_id(vector):
        key = vector_key(vector)
        if key not in belief_id_by_key:
            belief_id_by_key[key] = len(belief_vectors)
            belief_vectors.append(vector)
        return belief_id_by_key[key]

    # Seed every possible post-localization state. A perfect update can reset
    # xhat,yhat to the actual robot position, so every free cell is a possible
    # exact-certainty starting knowledge context.
    queue = deque()
    seen_contexts = set()
    context_records = {}
    transitions = {}

    for x, y in free_cells(map_data):
        # Recenter certainty at the selected reset location.
        absolute = {(x, y): 1.0}
        vector = belief_impl._relative_vector(
            absolute, x, y, n
        )
        bid = get_belief_id(vector)
        key = (x, y, vector_key(vector))

        if key not in seen_contexts:
            seen_contexts.add(key)
            queue.append((x, y, vector, 0))
            context_records[key] = {
                "xhat": x,
                "yhat": y,
                "belief_id": bid,
                "min_depth": 0,
            }

    max_depth_seen = 0
    expanded_contexts = 0
    stopped_by_tau10 = 0
    stopped_by_target = 0
    stopped_by_no_action = 0

    while queue:
        xhat, yhat, vector, depth = queue.popleft()
        max_depth_seen = max(max_depth_seen, depth)

        key = (xhat, yhat, vector_key(vector))
        bid = get_belief_id(vector)
        uncertainty = scaled_gini(vector)

        context_records[key].update({
            "belief_id": bid,
            "uncertainty": uncertainty,
        })

        # If the largest threshold has been reached, then every possible URC
        # choice c=1..10 would trigger update. No skip successor is needed.
        if uncertainty >= tau_max:
            stopped_by_tau10 += 1
            context_records[key]["terminal_reason"] = "tau10"
            continue

        if (xhat, yhat) == target:
            stopped_by_target += 1
            context_records[key]["terminal_reason"] = "target"
            continue

        action = belief_impl._direction(
            controller, xhat, yhat
        )
        if action is None:
            stopped_by_no_action += 1
            context_records[key]["terminal_reason"] = "no_action"
            continue

        successor, nxhat, nyhat = exact_successor(
            vector, xhat, yhat, action, n, p
        )
        next_bid = get_belief_id(successor)
        next_key = (
            nxhat,
            nyhat,
            vector_key(successor),
        )

        transitions[key] = {
            "action": action,
            "next_xhat": nxhat,
            "next_yhat": nyhat,
            "next_belief_id": next_bid,
        }
        expanded_contexts += 1

        if next_key not in seen_contexts:
            seen_contexts.add(next_key)
            queue.append(
                (nxhat, nyhat, successor, depth + 1)
            )
            context_records[next_key] = {
                "xhat": nxhat,
                "yhat": nyhat,
                "belief_id": next_bid,
                "min_depth": depth + 1,
            }
        else:
            context_records[next_key]["min_depth"] = min(
                context_records[next_key]["min_depth"],
                depth + 1,
            )

    # Count physically reachable (x,y,xhat,yhat,belief_id) combinations.
    # For a given exact belief context, every state in its positive-probability
    # support is a reachable physical state of the DTMC.
    joint_states = set()
    support_sizes = []

    for key, record in context_records.items():
        xhat = record["xhat"]
        yhat = record["yhat"]
        bid = record["belief_id"]
        vector = belief_vectors[bid]
        absolute = absolute_from_relative(
            vector, xhat, yhat, n
        )
        support = [
            (x, y)
            for (x, y), prob in absolute.items()
            if prob > 1e-15
        ]
        support_sizes.append(len(support))

        for x, y in support:
            joint_states.add(
                (x, y, xhat, yhat, bid)
            )

    # Some distinct contexts may share the same relative belief ID. This is
    # desirable: the PRISM variable can store only the belief ID while xhat,
    # yhat remain separate variables.
    exact_belief_count = len(belief_vectors)
    exact_context_count = len(context_records)

    horizon_exact_belief_count = len(
        {
            vector_key(item["vector"])
            for item in horizon_candidates
        }
    )

    summary = {
        "map_id": map_id,
        "free_cells": len(free_cells(map_data)),
        "max_steps_for_thresholds": max_steps,
        "thresholds": thresholds,
        "tau10": tau_max,

        "horizon_exact_belief_count": (
            horizon_exact_belief_count
        ),

        "urc_closed_exact_belief_count": (
            exact_belief_count
        ),
        "urc_closed_knowledge_context_count": (
            exact_context_count
        ),
        "urc_closed_physical_knowledge_state_count": (
            len(joint_states)
        ),

        "mean_belief_support_size": (
            sum(support_sizes) / len(support_sizes)
            if support_sizes else 0.0
        ),
        "max_belief_support_size": (
            max(support_sizes)
            if support_sizes else 0
        ),

        "max_skip_depth_before_forced_update": (
            max_depth_seen
        ),
        "expanded_contexts": expanded_contexts,
        "terminal_tau10_contexts": stopped_by_tau10,
        "terminal_target_contexts": stopped_by_target,
        "terminal_no_action_contexts": (
            stopped_by_no_action
        ),

        # Direct comparison with old K=100 abstraction.
        "belief_id_factor_vs_k100": (
            exact_belief_count / 100.0
        ),
    }

    return summary, context_records, transitions


def write_csv(path, rows):
    if not rows:
        return

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=list(rows[0].keys()),
        )
        writer.writeheader()
        writer.writerows(rows)


def parse_maps(value):
    if value is None:
        return list(
            range(DEFAULT_FIRST_MAP, DEFAULT_LAST_MAP + 1)
        )

    result = []
    for item in value.split(","):
        item = item.strip()
        if not item:
            continue
        if "-" in item:
            start, end = item.split("-", 1)
            result.extend(
                range(int(start), int(end) + 1)
            )
        else:
            result.append(int(item))
    return sorted(set(result))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--maps",
        default=None,
        help="e.g. 10 or 10,14,23 or 10-99",
    )
    parser.add_argument(
        "--maps-dir",
        default=DEFAULT_MAPS_DIR,
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
    )
    parser.add_argument(
        "--p",
        type=float,
        default=DEFAULT_P,
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=DEFAULT_MAX_STEPS,
    )
    parser.add_argument(
        "--target-x",
        type=int,
        default=DEFAULT_TARGET[0],
    )
    parser.add_argument(
        "--target-y",
        type=int,
        default=DEFAULT_TARGET[1],
    )
    args = parser.parse_args()

    maps = parse_maps(args.maps)
    target = (args.target_x, args.target_y)

    output_root = Path(args.output_dir)
    output_root.mkdir(
        parents=True, exist_ok=True
    )

    all_rows = []

    for map_id in maps:
        path = Path(args.maps_dir) / f"map_{map_id}.csv"

        if not path.exists():
            print(
                f"Skipping map {map_id}: {path} not found"
            )
            continue

        print(f"\nAnalysing map {map_id} ...")
        map_data = load_map(path)

        summary, contexts, transitions = analyse_map(
            map_id=map_id,
            map_data=map_data,
            target=target,
            p=args.p,
            max_steps=args.max_steps,
        )

        all_rows.append(summary)

        map_dir = output_root / f"map_{map_id}"
        map_dir.mkdir(
            parents=True, exist_ok=True
        )

        with (
            map_dir / "summary.json"
        ).open("w", encoding="utf-8") as f:
            json.dump(
                summary,
                f,
                indent=2,
            )

        context_rows = []
        for key, record in contexts.items():
            context_rows.append({
                "xhat": record["xhat"],
                "yhat": record["yhat"],
                "belief_id": record["belief_id"],
                "uncertainty": record.get(
                    "uncertainty", ""
                ),
                "min_depth": record["min_depth"],
                "terminal_reason": record.get(
                    "terminal_reason", ""
                ),
            })

        write_csv(
            map_dir / "knowledge_contexts.csv",
            context_rows,
        )

        transition_rows = []
        for key, transition in transitions.items():
            xhat, yhat, _ = key
            record = contexts[key]
            transition_rows.append({
                "xhat": xhat,
                "yhat": yhat,
                "belief_id": record["belief_id"],
                "action": transition["action"],
                "next_xhat": transition["next_xhat"],
                "next_yhat": transition["next_yhat"],
                "next_belief_id": (
                    transition["next_belief_id"]
                ),
            })

        write_csv(
            map_dir / "exact_transitions.csv",
            transition_rows,
        )

        print(
            "  exact beliefs within threshold horizon: "
            f"{summary['horizon_exact_belief_count']}"
        )
        print(
            "  URC-closed exact belief IDs: "
            f"{summary['urc_closed_exact_belief_count']}"
        )
        print(
            "  reachable (xhat,yhat,belief) contexts: "
            f"{summary['urc_closed_knowledge_context_count']}"
        )
        print(
            "  reachable (x,y,xhat,yhat,belief) combinations: "
            f"{summary['urc_closed_physical_knowledge_state_count']}"
        )
        print(
            "  max skip depth before tau10 forces update: "
            f"{summary['max_skip_depth_before_forced_update']}"
        )
        print(
            "  factor exact belief IDs vs K=100: "
            f"{summary['belief_id_factor_vs_k100']:.2f}x"
        )

    write_csv(
        output_root / "all_maps_summary.csv",
        all_rows,
    )

    if all_rows:
        def mean(field):
            return sum(
                float(r[field]) for r in all_rows
            ) / len(all_rows)

        aggregate = {
            "maps": len(all_rows),
            "mean_horizon_exact_belief_count": mean(
                "horizon_exact_belief_count"
            ),
            "mean_urc_closed_exact_belief_count": mean(
                "urc_closed_exact_belief_count"
            ),
            "mean_urc_closed_knowledge_context_count": mean(
                "urc_closed_knowledge_context_count"
            ),
            "mean_urc_closed_physical_knowledge_state_count": mean(
                "urc_closed_physical_knowledge_state_count"
            ),
            "mean_max_skip_depth_before_forced_update": mean(
                "max_skip_depth_before_forced_update"
            ),
            "mean_belief_id_factor_vs_k100": mean(
                "belief_id_factor_vs_k100"
            ),
        }

        with (
            output_root / "aggregate.json"
        ).open("w", encoding="utf-8") as f:
            json.dump(
                aggregate,
                f,
                indent=2,
            )

        print("\nAggregate:")
        print(
            "  mean URC-closed exact belief IDs: "
            f"{aggregate['mean_urc_closed_exact_belief_count']:.2f}"
        )
        print(
            "  mean reachable knowledge contexts: "
            f"{aggregate['mean_urc_closed_knowledge_context_count']:.2f}"
        )
        print(
            "  mean reachable physical+knowledge combinations: "
            f"{aggregate['mean_urc_closed_physical_knowledge_state_count']:.2f}"
        )


if __name__ == "__main__":
    main()
