PROBLEM = ROBOT10_REP9
       MODEL_TEMPLATE_FILE = models/model_10_umc.prism
       PROPERTIES_FILE = robot.pctl
       ALGORITHM = NSGAII
       POPULATION_SIZE = 50
       MAX_EVALUATIONS = 1000
       PROCESSORS = 4
       PLOT_PARETO_FRONT = false
       VERBOSE = true
       INIT_PORT = 11090
