PROBLEM = ROBOT14_REP9
       MODEL_TEMPLATE_FILE = models/model_14_umc.prism
       PROPERTIES_FILE = robot.pctl
       ALGORITHM = NSGAII
       POPULATION_SIZE = 100
       MAX_EVALUATIONS = 4000
       PROCESSORS = 4
       PLOT_PARETO_FRONT = false
       VERBOSE = true
       INIT_PORT = 11490
