PROBLEM = ROBOT47_REP8
       MODEL_TEMPLATE_FILE = models/model_47_umc.prism
       PROPERTIES_FILE = robot.pctl
       ALGORITHM = NSGAII
       POPULATION_SIZE = 100
       MAX_EVALUATIONS = 4000
       PROCESSORS = 6
       PLOT_PARETO_FRONT = false
       VERBOSE = true
       INIT_PORT = 14780
