PROBLEM = ROBOT90_REP9
       MODEL_TEMPLATE_FILE = models/model_90_umc.prism
       PROPERTIES_FILE = robot.pctl
       ALGORITHM = NSGAII
       POPULATION_SIZE = 100
       MAX_EVALUATIONS = 4000
       PROCESSORS = 6
       PLOT_PARETO_FRONT = false
       VERBOSE = true
       INIT_PORT = 19090
