PROBLEM = ROBOT_INTERVAL_RQ3_MAP2_REP6
       MODEL_TEMPLATE_FILE = models/model_interval_2_umc.prism
       PROPERTIES_FILE = robot_rq3_map_2.pctl
       ALGORITHM = NSGAII
       POPULATION_SIZE = 100
       MAX_EVALUATIONS = 200
       PROCESSORS = 1
       PLOT_PARETO_FRONT = false
       VERBOSE = true
       INIT_PORT = 10260
